import { DOStatus } from '@/models';
import { ActionType, EditableProTable } from '@ant-design/pro-table';
import { nanoid } from '@reduxjs/toolkit';
import { PlusOutlined } from '@ant-design/icons';
import { useSelector, useDispatch } from 'react-redux';
import { Form, Space, Button } from 'antd';
import { FC, useRef, useState, useEffect } from 'react';
import styles from './styles.less';
import { actions } from '../store';
import {} from '../../../../models';
import { useFgDisabled, useFormData, useEditStatusInfo } from '../hooks';
