import { TBillFormContent } from '@/models';

const tableConf: TBillFormContent | undefined = {
  action: 1,
  billFormType: 'Single',
  componentModuleName: '主模块',
  componentName: '摄像头',
  displayName: '摄像头',
  idBillForm: 'bIMoCsuJqy_ywVLrbG9wV',
  idComponent: 'BWJfLiVp79Fgju0ovtDFP',
  idComponentModule: '54dAchFyvvdIbz37X1mI-',
  idProject: 'HUo86fGpkXtIrqPKvjct0',
  idSubProject: '8JTsJB_8DgDd9eb__CfYT',
  name: 'camera',
  projectName: 'rtsp2rtmp',
  subProjectName: 'main',
  configList: {
    idBillForm: 'mgXBK1IFomL_XrfxB9hv8',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'xekgJ_RPuvAJqAfEKnWvO',
        tabCode: 'camera',
        tabName: '摄像头',
        tabIndex: 0,
        billFormFields: [
          {
            idBillFormField: 'HVawC0zevGUtsqPKiiB3Y',
            name: 'id',
            displayName: '摄像头主属性',
            fgMainProperty: true,
            showOrder: 0,
            readonly: false,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'gs1CLp_uFPXG0OyWmhY4e',
            name: 'code',
            displayName: '编号',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'hWwr4GDhA9Tx0gENEs02u',
            name: 'rtspUrl',
            displayName: 'rtsp地址',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'g8C5OT6gwJ434LUwyr1mc',
            name: 'rtmpUrl',
            displayName: 'rtmp推送地址',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'A0i7diWL623TyNffUldYu',
            name: 'playAuthCode',
            displayName: '播放权限码',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: '5FOqOkEZ0KwKcs0AdYpOC',
            name: 'onlineStatus',
            displayName: '在线状态',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'iDr679_jfpLcew-Cl8Sak',
            name: 'enabled',
            displayName: '启用状态',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'hRBQ0BK4luWVwcVwuhVRN',
            name: 'rtmpPushStatus',
            displayName: 'rtmp推送状态',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: '-7IC9rYRH57qQvAs3MKvf',
            name: 'saveVideo',
            displayName: '保存录像状态',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'yBJhtb1Tjz6foa2t9xErZ',
            name: 'live',
            displayName: '直播状态',
            fgMainProperty: false,
            showOrder: 9,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'owqfUWAqFWw0qwbzMF7iw',
            name: 'cameraType',
            displayName: '摄像头类型',
            fgMainProperty: false,
            showOrder: 10,
            readonly: false,
            dataType: 'String',
            inputType: 'Select',
            fgDisplay: true,
            enumConfig: {
              idEnumRef: 'g0dZkl9ZyR2LKQrt2ElHK',
              enumColumns: [
                {
                  idEnumColumn: 'D9zB-bnfoT4x_jgXBCZ7l',
                  code: 'RTMP',
                  displayName: 'RTMP摄像头',
                  enumValue: 'rtmp',
                },
                {
                  idEnumColumn: 'N7tOA07eUkLTDbQM7i9TC',
                  code: 'RTSP',
                  displayName: 'RTSP摄像头',
                  enumValue: 'rtsp',
                },
              ],
              label: '摄像头类型',
              propertyName: 'cameraType',
              title: '摄像头类型',
            },
          },
          {
            idBillFormField: 'Pqe_jMDbBtGUgsh5bc0PP',
            name: 'fgPassive',
            displayName: '被动推送rtmp标志',
            fgMainProperty: false,
            showOrder: 11,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'uvLJMKAIfj4vXzoCGL44K',
            name: 'rtmpAuthCode',
            displayName: 'rtmp识别码',
            fgMainProperty: false,
            showOrder: 12,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'zAvfMNbW12ZXV69UmWP1w',
            name: 'fgEncrypt',
            displayName: '加密标志',
            fgMainProperty: false,
            showOrder: 13,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: '-BdqecWmqTg_6eZMtKG_5',
            name: 'created',
            displayName: '创建时间',
            fgMainProperty: false,
            showOrder: 14,
            readonly: false,
            dataType: 'DateTime',
            inputType: 'DateTime',
            fgDisplay: true,
          },
        ],
        metadataAttrName: 'camera',
        firstUpperTabCode: 'Camera',
        tabClassName: 'Camera',
        firstLowerTabClassName: 'camera',
        tabAttrName: 'camera',
        firstUpperTabAttrName: 'Camera',
        mainProperty: 'id',
        refType: 'Single',
        orderProperty: 'id',
        orderType: 'ASC',
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      page: '/camera/aqPage',
      fetchById: '/camera/getById',
      batchRemove: '/camera/batchRemove',
    },
  },
  configForm: {
    idBillForm: 'mgXBK1IFomL_XrfxB9hv8',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'xekgJ_RPuvAJqAfEKnWvO',
        tabCode: 'camera',
        tabName: '摄像头',
        tabIndex: 0,
        billFormFields: [
          {
            idBillFormField: 'HVawC0zevGUtsqPKiiB3Y',
            name: 'id',
            displayName: '摄像头主属性',
            fgMainProperty: true,
            showOrder: 0,
            readonly: true,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'gs1CLp_uFPXG0OyWmhY4e',
            name: 'code',
            displayName: '编号',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'hWwr4GDhA9Tx0gENEs02u',
            name: 'rtspUrl',
            displayName: 'rtsp地址',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'g8C5OT6gwJ434LUwyr1mc',
            name: 'rtmpUrl',
            displayName: 'rtmp推送地址',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'A0i7diWL623TyNffUldYu',
            name: 'playAuthCode',
            displayName: '播放权限码',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: '5FOqOkEZ0KwKcs0AdYpOC',
            name: 'onlineStatus',
            displayName: '在线状态',
            fgMainProperty: false,
            showOrder: 5,
            readonly: true,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'iDr679_jfpLcew-Cl8Sak',
            name: 'enabled',
            displayName: '启用状态',
            fgMainProperty: false,
            showOrder: 6,
            readonly: true,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'hRBQ0BK4luWVwcVwuhVRN',
            name: 'rtmpPushStatus',
            displayName: 'rtmp推送状态',
            fgMainProperty: false,
            showOrder: 7,
            readonly: true,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: '-7IC9rYRH57qQvAs3MKvf',
            name: 'saveVideo',
            displayName: '保存录像状态',
            fgMainProperty: false,
            showOrder: 8,
            readonly: true,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'yBJhtb1Tjz6foa2t9xErZ',
            name: 'live',
            displayName: '直播状态',
            fgMainProperty: false,
            showOrder: 9,
            readonly: true,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: '-BdqecWmqTg_6eZMtKG_5',
            name: 'created',
            displayName: '创建时间',
            fgMainProperty: false,
            showOrder: 10,
            readonly: true,
            dataType: 'DateTime',
            inputType: 'DateTime',
            fgDisplay: true,
          },
          {
            idBillFormField: 'JZre5FiVypK8QhOq0jy_U',
            name: 'fgPassive',
            displayName: '被动推送rtmp标志',
            fgMainProperty: false,
            showOrder: 11,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'HQIEc4EAlnU3v4Nz2SC3p',
            name: 'rtmpAuthCode',
            displayName: 'rtmp识别码',
            fgMainProperty: false,
            showOrder: 12,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'QvTs08SnjWsWkbmmQd7kL',
            name: 'fgEncrypt',
            displayName: '加密标志',
            fgMainProperty: false,
            showOrder: 13,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'eyzi2X3yKd31lxUqC60K5',
            name: 'cameraType',
            displayName: '摄像头类型',
            fgMainProperty: false,
            showOrder: 14,
            dataType: 'String',
            inputType: 'Select',
            fgDisplay: true,
            enumConfig: {
              idEnumRef: 'Muy2whmKVTxbVlX7eolvD',
              enumColumns: [
                {
                  idEnumColumn: 'BYGqGIJMnQ1Cf_hrBZ3PL',
                  code: 'RTMP',
                  displayName: 'RTMP摄像头',
                  enumValue: 'rtmp',
                },
                {
                  idEnumColumn: 'lz5luRbGXAxeLPf4groaL',
                  code: 'RTSP',
                  displayName: 'RTSP摄像头',
                  enumValue: 'rtsp',
                },
              ],
              label: '摄像头类型',
              propertyName: 'cameraType',
              title: '摄像头类型',
            },
          },
        ],
        metadataAttrName: 'camera',
        firstUpperTabCode: 'Camera',
        tabClassName: 'Camera',
        firstLowerTabClassName: 'camera',
        tabAttrName: 'camera',
        firstUpperTabAttrName: 'Camera',
        mainProperty: 'id',
        refType: 'Single',
        orderProperty: 'id',
        orderType: 'ASC',
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      fetchById: '/camera/getById',
      save: '/camera/add',
      update: '/camera/update',
      dataRemove: '/camera/remove',
    },
  },
};

export { tableConf };
