import { TQueryContent } from '@/models';

const queryConf: TQueryContent | undefined = {
  action: 1,
  componentModuleName: '主模块',
  componentName: null,
  displayName: '摄像头',
  idComponent: 'BWJfLiVp79Fgju0ovtDFP',
  idComponentModule: '54dAchFyvvdIbz37X1mI-',
  idProject: 'HUo86fGpkXtIrqPKvjct0',
  idQuery: 'CIkbiLHPbUIPVa9ICE3xC',
  idSubProject: '8JTsJB_8DgDd9eb__CfYT',
  name: 'camera-query',
  projectName: 'rtsp2rtmp',
  subProjectName: 'main',
  searchRefs: [
    {
      idBillSearchRef: 't13gJUypw71xV-suEHiBM',
      operatorCode: 'like',
      label: '编号',
      attributeName: 'code',
      searchAttributes: ['code'],
      htmlInputType: 'Input',
      valueType: 'String',
      defaultValue: '',
      showOrder: 0,
    },
    {
      idBillSearchRef: '7lNfC7wnV--T4jjEEummD',
      operatorCode: 'like',
      label: 'rtsp地址',
      attributeName: 'rtspUrl',
      searchAttributes: ['rtspUrl'],
      htmlInputType: 'Input',
      valueType: 'String',
      defaultValue: '',
      showOrder: 1,
    },
    {
      idBillSearchRef: 'YxQS9mTJcmDVlKP1Ccwtm',
      operatorCode: 'equal',
      label: '启用状态',
      attributeName: 'enabled',
      searchAttributes: ['enabled'],
      htmlInputType: 'Select',
      valueType: 'Bool',
      defaultValue: 'all',
      enumConfig: {
        idEnumRef: 'lxJGiqxLKKNH-27LlJ66r',
        enumColumns: [
          {
            idEnumColumn: 'Qj9IoejxV2a4y73YsgTUz',
            displayName: '全部',
            code: 'all',
            enumValue: 'all',
          },
          {
            idEnumColumn: 'AE0u0wCDMNw8ClY-PmvNG',
            displayName: '是',
            enumValue: 'true',
            code: 'true',
          },
          {
            idEnumColumn: 'qg3uWGTyyIEb2C7iPI28V',
            displayName: '否',
            enumValue: 'false',
            code: 'false',
          },
        ],
      },
      showOrder: 2,
    },
    {
      idBillSearchRef: '1RmEALmiBaLGgTOy612L0',
      operatorCode: 'equal',
      label: '在线状态',
      attributeName: 'onlineStatus',
      searchAttributes: ['onlineStatus'],
      htmlInputType: 'Select',
      valueType: 'Bool',
      defaultValue: 'all',
      enumConfig: {
        idEnumRef: '71jsYQIw33k2xQNhIDlZ_',
        enumColumns: [
          {
            idEnumColumn: 'yckkkKRsdbCkCD1Co-EPF',
            displayName: '全部',
            code: 'all',
            enumValue: 'all',
          },
          {
            idEnumColumn: 'qIoIj3zjTWUZTEpLsYIvk',
            displayName: '是',
            enumValue: 'true',
            code: 'true',
          },
          {
            idEnumColumn: 'jfn9Udlo6OJtC-RZG9EMX',
            displayName: '否',
            enumValue: 'false',
            code: 'false',
          },
        ],
      },
      showOrder: 3,
    },
    {
      idBillSearchRef: '4F3Ojkc8mJ0t1iJ-vw7-o',
      operatorCode: 'like',
      label: '摄像头类型',
      attributeName: 'cameraType',
      searchAttributes: ['cameraType'],
      htmlInputType: 'Select',
      valueType: 'String',
      defaultValue: '',
      enumConfig: {
        idEnumRef: 'hadnZxmL-pzvy-rm4YCv6',
        enumColumns: [
          {
            idEnumColumn: 'MFj6wlsVBZ9z1822yXYcm',
            displayName: 'RTMP摄像头',
            enumValue: 'rtmp',
            code: 'RTMP',
          },
          {
            idEnumColumn: '_YosdYbM29sy4vUK7bw4z',
            displayName: 'RTSP摄像头',
            enumValue: 'rtsp',
            code: 'RTSP',
          },
        ],
      },
      showOrder: 4,
    },
    {
      idBillSearchRef: 'tDPqjyJa4tjtatLSeoJDY',
      operatorCode: 'equal',
      label: '被动推送rtmp标志',
      attributeName: 'fgPassive',
      searchAttributes: ['fgPassive'],
      htmlInputType: 'Select',
      valueType: 'Bool',
      defaultValue: 'all',
      enumConfig: {
        idEnumRef: 'IArpRbyf73zrG_64Wclb_',
        enumColumns: [
          {
            idEnumColumn: 'E0wu4MXCBFdp6lpDQ0Ym3',
            displayName: '全部',
            enumValue: 'all',
            code: 'all',
          },
          {
            idEnumColumn: 'nwOfoo3KEdfsRsXTtvcp3',
            displayName: '是',
            enumValue: 'true',
            code: 'true',
          },
          {
            idEnumColumn: 'SvSERAyopH1WRj4lgSiOb',
            displayName: '否',
            enumValue: 'false',
            code: 'false',
          },
        ],
      },
      showOrder: 5,
    },
    {
      idBillSearchRef: 'jU3_87kdKpRc_7njyjYrq',
      operatorCode: 'equal',
      label: '加密标志',
      attributeName: 'fgSecret',
      searchAttributes: ['fgSecret'],
      htmlInputType: 'Select',
      valueType: 'Bool',
      defaultValue: 'all',
      enumConfig: {
        idEnumRef: 'dgR_nm4DSS0nh0EUZQT1P',
        enumColumns: [
          {
            idEnumColumn: 'ZVdkHpDESrxWM_j3Vz7g_',
            displayName: '全部',
            enumValue: 'all',
            code: 'all',
          },
          {
            idEnumColumn: 'YGWJr5NoV_SuYJszSEX7s',
            displayName: '是',
            enumValue: 'true',
            code: 'true',
          },
          {
            idEnumColumn: 'zuzhhrN_ZgqYy1pR-CLaA',
            displayName: '否',
            enumValue: 'false',
            code: 'false',
          },
        ],
      },
      showOrder: 6,
    },
  ],
};

export { queryConf };
