import { TUiFactoryContent } from '@/models';

const layoutConf: TUiFactoryContent = {
  action: 1,
  componentModuleName: '系统模块',
  componentName: null,
  displayName: '系统用户聚合',
  fgTemplate: false,
  idComponent: '7rMPYMEiFYWA5tnZcqYUX',
  idComponentModule: 'NUWZLV-HXSQY7up9bY58k',
  idFactory: 'gY2is_txKK19xRL4jmd3P',
  idProject: '0000-fe135b87-fb33-481f-81a6-53dff1808f43',
  idSubProject: '0000-bb004a40-3b38-4c9c-9f30-b69a543b0598',
  name: 'Useragg',
  projectName: '模板代码设计工具RUST',
  refIdContent: null,
  subProjectName: '模型管理',
  pages: [
    { key: 'index', id: 'index', code: 'index', name: '首页' },
    {
      key: 'qJXa0UfTIO6aKGDyRK591',
      id: 'qJXa0UfTIO6aKGDyRK591',
      code: 'edit',
      name: '编辑页',
    },
  ],
  layouts: [
    {
      key: 'root',
      id: 'root',
      title: 'root',
      idParent: null,
      order: 1,
      type: 'layout',
      direction: 'column',
      flexType: 'auto',
      flexStr: '1 1 auto',
      children: [
        {
          key: 'H6FTe1dBekbr97pqRvzHM',
          id: 'H6FTe1dBekbr97pqRvzHM',
          title: '查询面板',
          idParent: 'root',
          order: 1,
          type: 'component',
          direction: 'row',
          flexType: 'notGrow',
          flexStr: '0 1 auto',
          children: [],
          component: {
            componentType: 'search',
            idRef: 'Wa8ghERQ2_vSliiwGmPTp',
            name: '系统用户聚合查询',
          },
        },
        {
          key: '98pdFD9XbLmCWvYYOc3ze',
          id: '98pdFD9XbLmCWvYYOc3ze',
          title: '列表按钮',
          idParent: 'root',
          order: 2,
          type: 'component',
          direction: 'row',
          flexType: 'notGrow',
          flexStr: '0 1 auto',
          children: [],
          component: {
            componentType: 'viewButton',
            idRef: '0000-be9070b2-6fb9-487a-8fcc-0abc34fdbf39',
            name: '表单列表按钮',
          },
          pageMaps: [
            {
              idPageMap: '0326ce17-fe77-45a6-870a-71781ef62c90',
              componentStateCode: 'list',
              pageCode: 'index',
            },
            {
              idPageMap: 'e1701655-b548-485c-be13-3d36f00346a3',
              componentStateCode: 'form',
              pageCode: 'edit',
            },
          ],
        },
        {
          key: 'CbgAlyjHO_SUxpmG3Ad5e',
          id: 'CbgAlyjHO_SUxpmG3Ad5e',
          title: '列表',
          idParent: 'root',
          order: 3,
          type: 'component',
          direction: 'row',
          flexType: 'auto',
          flexStr: '1 1 auto',
          children: [],
          component: {
            componentType: 'viewBillform',
            idRef: 'WZM5vb4SOW0bPJ7szX5iS',
            name: '系统用户聚合',
          },
        },
        {
          key: 'oRt-4y7yx4N4XjBvmJJFF',
          id: 'oRt-4y7yx4N4XjBvmJJFF',
          title: '卡片按钮',
          idParent: 'root',
          order: 4,
          type: 'component',
          direction: 'row',
          flexType: 'notGrow',
          flexStr: '0 1 auto',
          children: [],
          component: {
            componentType: 'editButton',
            idRef: '0000-e17f1494-779f-46a2-9096-03598277a0f9',
            name: '表单编辑按钮',
          },
        },
        {
          key: '7Dwdniebj0nW5uIKoI1mc',
          id: '7Dwdniebj0nW5uIKoI1mc',
          title: '表单',
          idParent: 'root',
          order: 5,
          type: 'component',
          direction: 'row',
          flexType: 'auto',
          flexStr: '1 1 auto',
          children: [],
          component: {
            componentType: 'editBillform',
            idRef: 'WZM5vb4SOW0bPJ7szX5iS',
            name: '系统用户聚合',
          },
          pageMaps: [
            {
              idPageMap: 'ba9901a6-6a83-4973-91c2-d8510800afe8',
              componentStateCode: 'list',
              pageCode: 'index',
            },
            {
              idPageMap: '2beb55f7-3edd-4932-9d26-9aeb0f48f838',
              componentStateCode: 'form',
              pageCode: 'edit',
            },
          ],
        },
      ],
    },
  ],
  assos: [
    { idPage: 'index', idLayout: 'root', hidden: false, disabled: false },
    {
      idPage: 'index',
      idLayout: 'H6FTe1dBekbr97pqRvzHM',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: '98pdFD9XbLmCWvYYOc3ze',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: 'CbgAlyjHO_SUxpmG3Ad5e',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'qJXa0UfTIO6aKGDyRK591',
      idLayout: 'H6FTe1dBekbr97pqRvzHM',
      hidden: true,
      disabled: false,
    },
    {
      idPage: 'qJXa0UfTIO6aKGDyRK591',
      idLayout: '98pdFD9XbLmCWvYYOc3ze',
      hidden: true,
      disabled: false,
    },
    {
      idPage: 'qJXa0UfTIO6aKGDyRK591',
      idLayout: 'CbgAlyjHO_SUxpmG3Ad5e',
      hidden: true,
      disabled: false,
    },
    {
      idPage: 'qJXa0UfTIO6aKGDyRK591',
      idLayout: 'root',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: 'oRt-4y7yx4N4XjBvmJJFF',
      hidden: true,
      disabled: false,
    },
    {
      idPage: 'qJXa0UfTIO6aKGDyRK591',
      idLayout: 'oRt-4y7yx4N4XjBvmJJFF',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: '7Dwdniebj0nW5uIKoI1mc',
      hidden: true,
      disabled: false,
    },
    {
      idPage: 'qJXa0UfTIO6aKGDyRK591',
      idLayout: '7Dwdniebj0nW5uIKoI1mc',
      hidden: false,
      disabled: false,
    },
  ],
};

export { layoutConf };
