import { TBillFormContent } from '@/models';

const billformConf: TBillFormContent | undefined = {
  action: 1,
  billFormType: 'Single',
  componentModuleName: '系统模块',
  componentName: '系统菜单',
  displayName: '系统菜单',
  idBillForm: 'sOGFb8hc2U8WZVy4ISJkT',
  idComponent: 'KIqhMnW5IZ8yYjy8Qu0ld',
  idComponentModule: 'NUWZLV-HXSQY7up9bY58k',
  idProject: '0000-fe135b87-fb33-481f-81a6-53dff1808f43',
  idSubProject: '0000-bb004a40-3b38-4c9c-9f30-b69a543b0598',
  name: 'Menu',
  projectName: '模板代码设计工具RUST',
  subProjectName: '模型管理',
  configList: {
    idBillForm: '43EdJmMUozLX6WXgAMulC',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'AYqFXHO-wDlWZ91mACa65',
        tabCode: 'menu',
        tabName: '系统菜单',
        tabIndex: 0,
        billFormFields: [
          {
            idBillFormField: 'DkQoAgiv-mXyRENMQyZFW',
            name: 'idMenu',
            displayName: '系统菜单id',
            fgMainProperty: true,
            showOrder: 0,
            readonly: true,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'X3JTm5cP8rzlPdK6Sg-I9',
            name: 'name',
            displayName: '名称',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: '16kVoKvVKMt4B2YfmhDE_',
            name: 'displayName',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'tMLtijsj7NxZZLpBLrjXB',
            name: 'fgShow',
            displayName: '显示标志',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'Ngw59HwKWObSEo8QqjeIt',
            name: 'query',
            displayName: '路由参数',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'zh9TPehUgbV_l6SAEJPdB',
            name: 'menuType',
            displayName: '菜单类型',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'kBWkvKmMrgH6q8XVS7CXR',
            name: 'fgActive',
            displayName: '启用标志',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'MB91WD0pOjeYaotacCbld',
            name: 'webPerms',
            displayName: '前端权限标识',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'j2PD2YcBHJyz554bjLRAS',
            name: 'servicePerms',
            displayName: '后台权限标识',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: '0W9ksCChDz0wNRQOuWQOA',
            name: 'idParent',
            dataType: 'InternalRef',
            displayName: '上级系统菜单',
            fgMainProperty: false,
            showOrder: 9,
            refAttributeName: 'parent',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '系统菜单',
              displayProp: 'displayName',
              backWriteProp: 'idMenu',
              tableRef: {
                dataUri: '/menu/aqPage',
                tableMainProp: 'idMenu',
                treeRefMainKey: 'idParent',
                idComponentEntity: 'UkyyDdtzsjoEluOjvY3l-',
                ceDisplayName: '系统菜单',
                refColumns: [
                  {
                    idBillRefColumn: 'nZA6ek4kTv-yj9NWrRUR1',
                    name: 'name',
                    displayName: '名称',
                  },
                  {
                    idBillRefColumn: 'auXHsMKvaE5c0hYGQNpJ5',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: '2sQObSeorVLBGbwxoNxQl',
                    name: 'fgShow',
                    displayName: '显示标志',
                  },
                  {
                    idBillRefColumn: 'N_x45boaXsgutafKt1cZ5',
                    name: 'menuType',
                    displayName: '菜单类型',
                  },
                  {
                    idBillRefColumn: 'v6L3m3utQLD6otXHmXKsY',
                    name: 'fgActive',
                    displayName: '启用标志',
                  },
                ],
              },
            },
            fgDisplay: true,
            fgTreeAttr: true,
          },
        ],
        metadataAttrName: 'menu',
        firstUpperTabCode: 'Menu',
        fgDefaultTab: true,
        tabClassName: 'Menu',
        firstLowerTabClassName: 'menu',
        tabAttrName: 'menu',
        firstUpperTabAttrName: 'Menu',
        mainProperty: 'idMenu',
        refType: 'Single',
        orderProperty: 'idMenu',
        orderType: 'ASC',
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      page: '/menu/aqPage',
      fetchById: '/menu/extGetById',
      batchRemove: '/menu/batchRemove',
    },
  },
  configForm: {
    idBillForm: '43EdJmMUozLX6WXgAMulC',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'AYqFXHO-wDlWZ91mACa65',
        tabCode: 'menu',
        tabName: '系统菜单',
        tabIndex: 0,
        billFormFields: [
          {
            idBillFormField: 'DkQoAgiv-mXyRENMQyZFW',
            name: 'idMenu',
            displayName: '系统菜单id',
            fgMainProperty: true,
            showOrder: 0,
            readonly: true,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'X3JTm5cP8rzlPdK6Sg-I9',
            name: 'name',
            displayName: '名称',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: '16kVoKvVKMt4B2YfmhDE_',
            name: 'displayName',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'tMLtijsj7NxZZLpBLrjXB',
            name: 'fgShow',
            displayName: '显示标志',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'Ngw59HwKWObSEo8QqjeIt',
            name: 'query',
            displayName: '路由参数',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'zh9TPehUgbV_l6SAEJPdB',
            name: 'menuType',
            displayName: '菜单类型',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'kBWkvKmMrgH6q8XVS7CXR',
            name: 'fgActive',
            displayName: '启用标志',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'MB91WD0pOjeYaotacCbld',
            name: 'webPerms',
            displayName: '前端权限标识',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'j2PD2YcBHJyz554bjLRAS',
            name: 'servicePerms',
            displayName: '后台权限标识',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: '0W9ksCChDz0wNRQOuWQOA',
            name: 'idParent',
            dataType: 'InternalRef',
            displayName: '上级系统菜单',
            fgMainProperty: false,
            showOrder: 9,
            refAttributeName: 'parent',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '系统菜单',
              displayProp: 'displayName',
              backWriteProp: 'idMenu',
              tableRef: {
                dataUri: '/menu/aqPage',
                tableMainProp: 'idMenu',
                treeRefMainKey: 'idParent',
                idComponentEntity: 'UkyyDdtzsjoEluOjvY3l-',
                ceDisplayName: '系统菜单',
                refColumns: [
                  {
                    idBillRefColumn: 'nZA6ek4kTv-yj9NWrRUR1',
                    name: 'name',
                    displayName: '名称',
                  },
                  {
                    idBillRefColumn: 'auXHsMKvaE5c0hYGQNpJ5',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: '2sQObSeorVLBGbwxoNxQl',
                    name: 'fgShow',
                    displayName: '显示标志',
                  },
                  {
                    idBillRefColumn: 'N_x45boaXsgutafKt1cZ5',
                    name: 'menuType',
                    displayName: '菜单类型',
                  },
                  {
                    idBillRefColumn: 'v6L3m3utQLD6otXHmXKsY',
                    name: 'fgActive',
                    displayName: '启用标志',
                  },
                ],
              },
            },
            fgDisplay: true,
            fgTreeAttr: true,
          },
        ],
        metadataAttrName: 'menu',
        firstUpperTabCode: 'Menu',
        fgDefaultTab: true,
        tabClassName: 'Menu',
        firstLowerTabClassName: 'menu',
        tabAttrName: 'menu',
        firstUpperTabAttrName: 'Menu',
        mainProperty: 'idMenu',
        refType: 'Single',
        orderProperty: 'idMenu',
        orderType: 'ASC',
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      fetchById: '/menu/extGetById',
      save: '/menu/add',
      update: '/menu/update',
      dataRemove: '/menu/remove',
    },
  },
};

export { billformConf };
